### ISSUE TITLE
SNAT Network to Network

### ISSUE THREAD

**Issue by micron10** [vel21ripn/ipset_natmap#1]
Hi 
is there options to make nat : 

10.0.0.0/18 to 192.168.0.0/24 ?

**Comment by vel21ripn** [comment]
No.
The main goal was to make many port-forwarding rules of the same type in the form of a single command.
Support for address-to-address translation is not yet implemented.

**Comment by micron10** [comment]
ok thanks

is interest if make full conna nat with ipset
